creation_rules:
  # - Jaub key-id: age1lxduvqtglrdj38m27gsa4akdu82keqwgh7r57ep3dcwf7uaref4qtafwy5
  # - Fcoh key-id: age1udkf02y0z9g3nk5yd4jxlkfu03lzmzlvv6uy30eq2mfa9n3fyu7su4mghy
  # - Prod key: age1nef2pmuzen5zrgd5k2ek5tvtch43l22dektr5a274kyq5ts0yggs5e0xk6
  # - newppr: age1704ydjhlggql9eejhxcr7gzdug7sr42mny78nvnmc83ecyc02qlsxhevmf
  # - newprd: age107c2evhrv8jf8a708sxds0vdpht6wt5jcu5paanpk7746n0p3u8qx23d3j
  - age:
      age1lxduvqtglrdj38m27gsa4akdu82keqwgh7r57ep3dcwf7uaref4qtafwy5,
      age1udkf02y0z9g3nk5yd4jxlkfu03lzmzlvv6uy30eq2mfa9n3fyu7su4mghy,
      age1nef2pmuzen5zrgd5k2ek5tvtch43l22dektr5a274kyq5ts0yggs5e0xk6,
      age1704ydjhlggql9eejhxcr7gzdug7sr42mny78nvnmc83ecyc02qlsxhevmf,
      age107c2evhrv8jf8a708sxds0vdpht6wt5jcu5paanpk7746n0p3u8qx23d3j

