apiVersion: v1
kind: Secret
metadata:
  name: ft-secret-app
type: Opaque
data:
{{- range $k, $v := .Values.ftSecret }}
  {{ $k }}: {{ $v }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ft-secret-dex
type: Opaque
data:
{{- range $k, $v := .Values.dexConfig }}
  {{ $k }}: {{ $v }}
{{- end }}
---