apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronbackup
  labels:
    tier: back
spec:
  schedule: {{ .Values.backup.schedule | default "20 4 * * *" }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  {{- if not .Values.backup.enabled }}
  suspend: true
  {{- end }}
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: backup
          restartPolicy: Never
          initContainers:
            - name: kubectlcp
              image: bitnami/kubectl
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "250m"
                limits:
                  memory: "256Mi"
                  cpu: "1"
              volumeMounts:
                - name: data
                  mountPath: /backup
                - name: backup-script
                  mountPath: /scripts
              command:
                - /bin/sh
                - "/scripts/redisdump.sh"
          containers:
            - name: s3
              image: mesosphere/aws-cli
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "250m"
                limits:
                  memory: "256Mi"
                  cpu: "250m"
              volumeMounts:
                - name: data
                  mountPath: /backup
                - name: backup-script
                  mountPath: /scripts
              envFrom:
                - configMapRef:
                    name: env-backup-s3
                - secretRef:
                    name: ft-secret-app
              command:
                - /bin/sh
                - "/scripts/backup.sh"
          restartPolicy: Never
          volumes:
            - name: backup-script
              configMap:
                defaultMode: 0770
                name: backup-script
            - name: data
              ephemeral:
                volumeClaimTemplate:
                  metadata:
                    labels:
                      type: tmpdata
                  spec:
                    accessModes: [ "ReadWriteOnce" ]
                    resources:
                      requests:
                        storage: 15Gi
