apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-copy
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","delete","watch"]
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-copy-rolebinding
subjects:
- kind: ServiceAccount
  name: backup
roleRef:
  kind: Role
  name: pod-copy
  apiGroup: rbac.authorization.k8s.io
