apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-scaler
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["get", "list","update","patch"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-scaler-rolebinding
subjects:
- kind: ServiceAccount
  name: scaler
roleRef:
  kind: Role
  name: pod-scaler
  apiGroup: rbac.authorization.k8s.io
