{{- if .Values.gateway.enabled }}
{{- $coraza := .Values.gateway.coraza }}
{{- if $coraza.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: waf-{{ include "france-transfert.fullname" . }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ include "france-transfert.fullname" . }}-rt
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ include "france-transfert.fullname" . }}-rt-upload
  dynamicModule:
    {{- range $coraza.dynamicModule }}
    - name: {{ .name }}
      filterName: {{ .filterName }}
      config:
        directives:
          {{- range .config.directives }}
          - {{ . }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}