{{- if gt (int .Values.download.replicaCount) 1 }}
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: {{ include "france-transfert.fullname" . }}-download-app-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "france-transfert.fullname" . }}-download-app
      release: {{ .Release.Name }}
      tier: back
{{ end }}
