apiVersion: v1
kind: Service
metadata:
  name: {{ include "france-transfert.fullname" . }}-download-service 
spec:
  selector:
    app: {{ include "france-transfert.fullname" . }}-download-app
    release: {{ .Release.Name }}
  ports:
  - port:  {{ .Values.download.service.port }}
    targetPort:  {{ .Values.download.service.targetPort }}
