{{- if .Values.front.hpa.enabled }}
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: {{ include "france-transfert.fullname" . }}-angular-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "france-transfert.fullname" . }}-angular-app
  minReplicas: {{ .Values.front.hpa.minReplicas }}
  maxReplicas: {{ .Values.front.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.front.hpa.cpu.averageUtilization }}
  behavior:
    {{- toYaml .Values.front.hpa.behavior | nindent 4 }}
{{- end }}
