{{- if .Values.maintenance.enabled }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: maintenance
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{.Values.ingress.className}}
  tls: {{.Values.ingress.tls | toYaml | nindent 2}}
  rules:
    {{- range $value := .Values.ingress.hosts }}
    - host: {{ $value }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: maintenance
                port:
                  number: 8080
    {{- end }}
{{- end }}