{{- if .Values.maintenance.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: maintenance
spec:
  selector:
    app: maintenance
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
{{- end }}