---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: fio-benchmark-job
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  suspend: true
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsUser: 3310101
            runAsGroup: 3310101
            fsGroup: 3310101
          containers:
          - name: fio
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
              seccompProfile:
                type: RuntimeDefault
              runAsNonRoot: true
              runAsUser: 3310101
              runAsGroup: 3310101
            image: ljishen/fio:latest
            command: ["/bin/sh", "-c"]
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                memory: 1Gi
            args:
              - fio --name=iops --numjobs=4 --ioengine=libaio --direct=1 --bs=4k --iodepth=128 --readwrite=randrw --directory=/data --size=1G --runtime=3600 --time_based --output-format=json --terse-version=5 --lat_percentiles=1 --clat_percentiles=0 --group_reporting
            volumeMounts:
            - name: fio-temp
              mountPath: /data
          restartPolicy: Never
          volumes:
          - name: fio-temp
            ephemeral:
              volumeClaimTemplate:
                metadata:
                  labels:
                    type: tmpbenchmark
                spec:
                  accessModes: [ "ReadWriteOnce" ]
                  {{ if .Values.benchmark.persistentVolumeClaim.storageClassName }}
                  storageClassName: {{ .Values.benchmark.persistentVolumeClaim.storageClassName }}
                  {{ end }}
                  resources:
                    requests:
                      storage: {{ .Values.benchmark.persistentVolumeClaim.storage }}
