apiVersion: v1
kind: Service
metadata:
  name: {{ include "france-transfert.fullname" . }}-upload-service
  labels:
    app: {{ include "france-transfert.fullname" . }}-upload-app
    release: {{ .Release.Name }}
    tier: back
spec:
  selector:
    app: {{ include "france-transfert.fullname" . }}-upload-app
    release: {{ .Release.Name }}
  ports:
  - port: {{ .Values.upload.service.port }}
    targetPort: {{ .Values.upload.service.targetPort }}
    name: http
  - port: {{ .Values.upload.service.managementPort }}
    targetPort: {{ .Values.upload.service.managementPort }}
    name: management
