name: Generic build
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      tag:
        required: true
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: 'maven'
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          override: false
          githubServer: true
      - name: Publish package
        run: mvn --batch-mode clean package
        working-directory: ${{ inputs.project }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.project }}
          push: true
          tags: |
            lasuite/${{ inputs.project }}:${{ inputs.tag }}
            lasuite/${{ inputs.project }}:${{ github.ref_name }}
