name: Publish Core
on:
  workflow_call:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Publish package
        run: mvn --batch-mode clean package deploy
        working-directory: francetransfert-core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
