name: Release

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: Release Tag
        required: true
        type: string
jobs:
  release:
    name: Create new release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: comnoco/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.TAG }}
          release_name: Release ${{ inputs.TAG }}
          body: |
            Release of ${{ inputs.TAG }}
          draft: false
          prerelease: false