name: Release

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: Release Tag
        required: true
        type: string
jobs:
  release:
    name: Create new release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4
      ##DO RELEASE
  build-core:
    needs: release
    uses: ./.github/workflows/core.yml
    secrets: inherit
  build-projects:
    needs: [build-core, release]
    strategy:
      matrix:
        project:
          [
            francetransfert-download-api,
            francetransfert-upload-api,
            francetransfert-worker,
          ]
    uses: ./.github/workflows/generic-build.yml
    secrets: inherit
    with:
      project: ${{ matrix.project }}
      tag: ${{ inputs.TAG }}
  build-front:
    needs: release
    uses: ./.github/workflows/build-front.yml
    secrets: inherit
    with:
      project: francetransfert-upload-download-gui
      tag: ${{ inputs.TAG }}
