{{- if .Values.worker.hpa.enabled }}
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: {{ include "france-transfert.fullname" . }}-worker-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    {{- if eq .Values.worker.type "sts" }}
    kind: StatefulSet
    {{- else if eq .Values.worker.type "deploy" }}
    kind: Deployment
    {{- end }}
    name: {{ include "france-transfert.fullname" . }}-worker-scaler
  minReplicas: {{ .Values.worker.hpa.minReplicas }}
  maxReplicas: {{ .Values.worker.hpa.maxReplicas }}
  metrics:
    {{- toYaml .Values.worker.hpa.metrics | nindent 4 }}
  behavior:
    {{- toYaml .Values.worker.hpa.behavior | nindent 4 }}
{{- end }}
