---
{{- if eq .Values.worker.type "sts" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "france-transfert.fullname" . }}-worker-app 
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "france-transfert.fullname" . }}-worker-app
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "france-transfert.fullname" . }}-worker-app
        release: {{ .Release.Name }}
        tier: back
    spec:
      terminationGracePeriodSeconds: {{ .Values.worker.terminationGracePeriodSeconds }}
      {{ if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{ end }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ include "france-transfert.fullname" . }}-worker-app
        image: {{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}
        imagePullPolicy: {{ .Values.worker.image.imagePullPolicy }}
        envFrom:
        - configMapRef:
            name: worker-override-conf-{{ .Release.Name }}
        - configMapRef:
            name: app-config-map-{{ .Release.Name }}
        - secretRef:
            name: ft-secret-app
        volumeMounts:
          - name: {{ include "france-transfert.fullname" . }}-worker-data
            mountPath: /data/
          - name: {{ include "france-transfert.fullname" . }}-worker-tmp
            mountPath: /tmp/
          - name: {{ include "france-transfert.fullname" . }}-worker-tmp
            mountPath: /opt/work/
          - name: config-volume
            mountPath: /dummy/
          - name: ft-keystore
            mountPath: /ft-keystore/
        resources:
          {{- toYaml .Values.worker.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.worker.securityContext | nindent 10 }}
      volumes:
        - name: config-volume
          configMap:
            name: worker-dummy
        - name: ft-keystore
          secret:
            secretName: ft-keystore
        - name: {{ include "france-transfert.fullname" . }}-worker-tmp
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: worker-tmp
              spec:
                accessModes: [ "ReadWriteOnce" ]
                {{ if .Values.worker.tmp.persistentVolumeClaim.storageClassName }}
                storageClassName: {{ .Values.worker.tmp.persistentVolumeClaim.storageClassName }}
                {{ end }}
                resources:
                  requests:
                    storage: {{ .Values.worker.tmp.persistentVolumeClaim.storage }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: {{ include "france-transfert.fullname" . }}-worker-app
        - minDomains: 3
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: {{ include "france-transfert.fullname" . }}-worker-app
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: {{ include "france-transfert.fullname" . }}-worker-app
                topologyKey: kubernetes.io/hostname
              weight: 1
  volumeClaimTemplates:
    - metadata:
        name: {{ include "france-transfert.fullname" . }}-worker-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{ if .Values.worker.data.persistentVolumeClaim.storageClassName }}
        storageClassName: {{ .Values.worker.data.persistentVolumeClaim.storageClassName }}
        {{ end }}
        resources:
          requests:
            storage: {{ .Values.worker.data.persistentVolumeClaim.storage }}
{{- end }}